
CREATE DATABASE TaskTwo;
GO

use TaskTwo;


CREATE TABLE Departments(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	Name VARCHAR(50) NOT NULL,
);


CREATE TABLE FeedBacks(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	Email VARCHAR(50) NOT NULL,
	RecievedDate DATETIME2 NULL,
	Content VARCHAR(MAX) NULL
);


CREATE TABLE ImportanceLevels(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	Name VARCHAR(30) NOT NULL,
);

CREATE TABLE Countries(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	Name VARCHAR(30) NOT NULL,
);

CREATE TABLE MaritalStatuses(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	Name VARCHAR(30) NOT NULL,
);


CREATE TABLE Managers(
	ID INT PRIMARY KEY,
	Name VARCHAR(50) NOT NULL,
);

CREATE TABLE Employees(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	Name VARCHAR(50) NOT NULL,
	BirthDate DATETIME2 NOT NULL,
	Phone VARCHAR(15) NULL,
	NationalID VARCHAR(15) NULL,
	NationalityID INT NOT NULL REFERENCES Countries(ID),
	MaritalStatusID INT NULL REFERENCES MaritalStatuses(ID),
	PersonalPhoto VARBINARY(MAX) NULL,
	EntryDate DATETIME2 NULL,
	Password VARCHAR(50) NOT NULL,
	DepartmentID INT NOT NULL REFERENCES Departments(ID)
);

CREATE TABLE PolicyRules(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	Name VARCHAR(30) NOT NULL,
);

CREATE TABLE Tasks(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	Title VARCHAR(50) NOT NULL,
	StartDate DATETIME2 NOT NULL,
	DueDate DATETIME2 NOT NULL,
	description VARCHAR(MAX) NOT NULL,
	ImportanceLevelID INT NULL REFERENCES ImportanceLevels(ID),
	EmployeeID INT NOT NULL REFERENCES Employees(ID),
	ManagerID INT NOT NULL REFERENCES Managers(ID)
);

CREATE TABLE EmployeesPolicyRules(            -- Junction table
	EmployeeID INT NOT NULL REFERENCES Employees(ID),
	PolicyID INT NOT NULL REFERENCES PolicyRules(ID),
	PRIMARY KEY(EmployeeID,PolicyID)
);


